# Generated by Django 3.2.4 on 2021-06-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polish_word",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "spanish_word",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("etymology", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True, max_length=2000, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
