# Generated by Django 3.2.4 on 2021-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0004_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='for_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
